### ISSUE TITLE
Homekit Bridge could not be started

### ISSUE THREAD

**Issue by paradiddle3** [Colorado4Wheeler/HomeKit-Bridge#129]
Hi - I'm trying to load Homekit Bridge for the first time (have not used Buddy in the past) on Indigo 7.2.   Homekit begins to load, and then fails, and stops each time.

**The Indigo logs i get is;

Apr 1, 2019 at 8:06:27 PM
   HomeKit Bridge Error            HomeKit server 'Apple Homekit Bridge' could not be started, please check the service logs for more information,
now issuing a forced shutdown of the service to be safe.

If you continue to have problems starting this server use the Advanced Plugin Actions menu option to rebuild the Homebridge folder.
Instructions at https://github.com/Colorado4Wheeler/HomeKit-Bridge/wiki/Plugin-Menu-Utilities#rebuild-homebridge-folder
   HomeKit Bridge                  Attempting to stop 'Apple Homekit Bridge'
   HomeKit Bridge                  HomeKit server 'Apple Homekit Bridge' has been stopped

**I've tried deleting and reloading Homekit, but get the same result.

**Here is the homebridge log that i get;

[2019-4-1 20:06:21] Loaded plugin: homebridge-camera-ffmpeg
[2019-4-1 20:06:21] Registering platform 'homebridge-camera-ffmpeg.Camera-ffmpeg'
[2019-4-1 20:06:21] ---
[2019-4-1 20:06:21] Loaded plugin: homebridge-indigo2
[2019-4-1 20:06:21] Registering platform 'homebridge-indigo2.Indigo2'
[2019-4-1 20:06:21] ---
[2019-4-1 20:06:21] Loaded config.json with 0 accessories and 1 platforms.
[2019-4-1 20:06:21] ---
[2019-4-1 20:06:21] Loading 1 platforms...
[2019-4-1 20:06:21] [HomeKit Bridge Server] Initializing Indigo2 platform...
[2019-4-1 20:06:21] [HomeKit Bridge Server] HomeKit Bridge base URL is http://127.0.0.1:8558
[2019-4-1 20:06:21] [HomeKit Bridge Server] HomeKit Bridge serverId is 1266873249
[2019-4-1 20:06:21] Loading 0 accessories...
Load homebridge-camera-ffmpeg.Camera-ffmpeg
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND localhost
    at errnoException (dns.js:50:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)

Please let me know what to try next.

thanks.

Paul

**Comment by Colorado4Wheeler** [comment]
> Loaded config.json with 0 accessories and 1 platforms.

Have you tried adding any devices to the HKB server to see what happens?  It could be having a problem because there aren't actually any devices to do something with.  Please also post the configuration file for Homebridge.

**Comment by paradiddle3** [comment]
Hi - thanks.   Yes, i've tried to add devices and get the same message.  I've attached a screen shot of the Accessory Server inputs.   Let me know if something looks off?

thanks.

![Screenshot 2019-04-02 09 16 11](https://user-images.githubusercontent.com/49174199/55405413-ff7d5480-5527-11e9-977c-156d3b81a39f.png)

Here's the config.json file contents...
{
        "platforms": [
                {
                        "protocol": "http", 
                        "name": "HomeKit Bridge Server", 
                        "listenPort": "8445", 
                        "platform": "Indigo2", 
                        "host": "127.0.0.1", 
                        "debug": false, 
                        "serverId": 1266873249, 
                        "port": "8558"
                }
        ], 
        "bridge": {
                "username": "CC:22:3D:E3:CE:10", 
                "name": "Apple Homekit Bridge", 
                "pin": "031-45-154", 
                "port": "51826"
        }, 
        "accessories": [], 
        "description": "HomeKit configuration generated by HomeKit Bridge on 2019-04-01 20:05:26.938000 for device Apple Homekit Bridge"
}

**Comment by paradiddle3** [comment]
Homekit Bridge began "running" miraculously yesterday.   However when i tried to link it to my iPhone (Home app) using the 031-45-154 code, it timed out, failed, and could not connect after several attempts.  

Does anyone have suggestions on what could be causing this?

thanks.

Paul

**Comment by Colorado4Wheeler** [comment]
Do you have it working on other iOS devices?

**Comment by paradiddle3** [comment]
No - and in fact today it's no longer "running" on Indigo, and I get the
prior messages about checking the file locations.

**Comment by rlust** [comment]
I am having the same issue, will not start any of my servers. I tried rebuild and no help. I deleted all servers and built new one. Same error messages as above.
